#include "level.h"

#include "room_data.h" // generated by tools/convert_rooms.py from assets/rooms/*.tmj

namespace game::level
{
    namespace
    {
        int active_room_index = 0;

        const room_data::room_def& active_room()
        {
            return room_data::rooms[active_room_index];
        }
    }

    spawn_point load_room(int room_index)
    {
        active_room_index = room_index;

        const room_data::room_def& room = active_room();
        return { to_fixed(room.spawn_x), to_fixed(room.spawn_y) };
    }

    int current_room_index()
    {
        return active_room_index;
    }

    bool current_room_is_save_room()
    {
        return active_room().is_save_room != 0;
    }

    spawn_point current_room_spawn_point()
    {
        const room_data::room_def& room = active_room();
        return { to_fixed(room.spawn_x), to_fixed(room.spawn_y) };
    }

    int room_platform_count()
    {
        return active_room().platform_count;
    }

    platform_view room_platform(int index)
    {
        const room_data::platform_def& p = active_room().platforms[index];
        return { p.x, p.y, p.width };
    }

    int room_enemy_spawn_count()
    {
        return active_room().enemy_spawn_count;
    }

    enemy_spawn_view room_enemy_spawn(int index)
    {
        const room_data::enemy_spawn_def& s = active_room().enemy_spawns[index];
        return { s.type, s.x, s.y };
    }

    fixed ground_top_y_at(fixed x)
    {
        const room_data::room_def& room = active_room();
        fixed best = no_ground_y;

        for(int i = 0; i < room.platform_count; ++i)
        {
            const room_data::platform_def& p = room.platforms[i];
            fixed left = to_fixed(p.x);
            fixed right = to_fixed(p.x + p.width);
            fixed top = to_fixed(p.y);

            if(x >= left && x <= right && top < best)
            {
                best = top;
            }
        }

        return best;
    }

    bool try_cross_door(fixed x, fixed y, spawn_point& out_spawn)
    {
        const room_data::room_def& room = active_room();

        for(int i = 0; i < room.door_count; ++i)
        {
            const room_data::door_def& d = room.doors[i];
            fixed left = to_fixed(d.x);
            fixed right = to_fixed(d.x + d.width);
            fixed top = to_fixed(d.y);
            fixed bottom = to_fixed(d.y + d.height);

            if(x >= left && x <= right && y >= top && y <= bottom)
            {
                out_spawn.x = to_fixed(d.target_x);
                out_spawn.y = to_fixed(d.target_y);
                load_room(d.target_room);
                return true;
            }
        }

        return false;
    }
}
