#!/usr/bin/env python3
"""Converts assets/rooms/*.json into GBA-ready C++ room data.

Rooms are data, not code (see CLAUDE.md's data-over-code rule) — this is
the build-time converter that rule calls for. It is wired into the root
Makefile's EXTTOOL hook, so it runs automatically before compilation.

This currently reads a small interim JSON schema (documented in
assets/rooms/README.md), not a real Tiled export — Tiled isn't installed
yet (see ROADMAP.md's M0 checklist). The schema mirrors what a Tiled
object layer exports (rectangle objects with x/y/width/height), so
swapping in real Tiled exports later should only mean changing this
script, not the room loader or the game logic that uses it.

Usage:
    convert_rooms.py --rooms-dir assets/rooms --build generated
"""
import argparse
import json
import os
import sys


def load_rooms(rooms_dir):
    rooms = []

    for name in sorted(os.listdir(rooms_dir)):
        if not name.endswith('.json'):
            continue

        path = os.path.join(rooms_dir, name)

        with open(path, 'r') as f:
            room = json.load(f)

        room['_source_file'] = name
        rooms.append(room)

    return rooms


def build_index(rooms):
    index = {}

    for i, room in enumerate(rooms):
        room_id = room['id']

        if room_id in index:
            raise ValueError('duplicate room id "%s" (%s)' % (room_id, room['_source_file']))

        index[room_id] = i

    return index


def write_header(path):
    with open(path, 'w') as f:
        f.write('#pragma once\n\n')
        f.write('// Generated by tools/convert_rooms.py from assets/rooms/*.json.\n')
        f.write('// Do not edit by hand.\n\n')
        f.write('namespace game::room_data\n{\n')
        f.write('    struct platform_def\n    {\n')
        f.write('        int x;\n        int y;\n        int width;\n')
        f.write('    };\n\n')
        f.write('    struct door_def\n    {\n')
        f.write('        int x;\n        int y;\n        int width;\n        int height;\n')
        f.write('        int target_room;\n        int target_x;\n        int target_y;\n')
        f.write('    };\n\n')
        f.write('    struct room_def\n    {\n')
        f.write('        const char* id;\n')
        f.write('        int spawn_x;\n        int spawn_y;\n')
        f.write('        const platform_def* platforms;\n        int platform_count;\n')
        f.write('        const door_def* doors;\n        int door_count;\n')
        f.write('    };\n\n')
        f.write('    extern const room_def rooms[];\n')
        f.write('    extern const int room_count;\n')
        f.write('}\n')


def cpp_string(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def write_source(path, rooms, index):
    with open(path, 'w') as f:
        f.write('#include "room_data.h"\n\n')
        f.write('// Generated by tools/convert_rooms.py from assets/rooms/*.json.\n')
        f.write('// Do not edit by hand.\n\n')
        f.write('namespace game::room_data\n{\n')

        for i, room in enumerate(rooms):
            platforms = room.get('platforms', [])
            doors = room.get('doors', [])

            f.write('    static const platform_def platforms_%d[] = {\n' % i)

            for p in platforms:
                f.write('        { %d, %d, %d },\n' % (p['x'], p['y'], p['width']))

            if not platforms:
                f.write('        { 0, 0, 0 },\n')

            f.write('    };\n\n')

            f.write('    static const door_def doors_%d[] = {\n' % i)

            for d in doors:
                if d['target_room'] not in index:
                    raise ValueError(
                        'room "%s" has a door targeting unknown room "%s"'
                        % (room['id'], d['target_room'])
                    )

                target = index[d['target_room']]
                f.write(
                    '        { %d, %d, %d, %d, %d, %d, %d },\n'
                    % (d['x'], d['y'], d['width'], d['height'], target, d['target_x'], d['target_y'])
                )

            if not doors:
                f.write('        { 0, 0, 0, 0, 0, 0, 0 },\n')

            f.write('    };\n\n')

        f.write('    const room_def rooms[] = {\n')

        for i, room in enumerate(rooms):
            spawn = room['spawn']
            f.write(
                '        { %s, %d, %d, platforms_%d, %d, doors_%d, %d },\n'
                % (
                    cpp_string(room['id']), spawn['x'], spawn['y'],
                    i, len(room.get('platforms', [])),
                    i, len(room.get('doors', [])),
                )
            )

        f.write('    };\n\n')
        f.write('    const int room_count = %d;\n' % len(rooms))
        f.write('}\n')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--rooms-dir', default='assets/rooms')
    parser.add_argument('--build', default='generated')
    args = parser.parse_args()

    rooms = load_rooms(args.rooms_dir)

    if not rooms:
        print('no room files found in %s' % args.rooms_dir, file=sys.stderr)
        sys.exit(1)

    index = build_index(rooms)

    include_dir = os.path.join(args.build, 'include')
    src_dir = os.path.join(args.build, 'src')
    os.makedirs(include_dir, exist_ok=True)
    os.makedirs(src_dir, exist_ok=True)

    write_header(os.path.join(include_dir, 'room_data.h'))
    write_source(os.path.join(src_dir, 'room_data.cpp'), rooms, index)

    print('converted %d room(s) from %s' % (len(rooms), args.rooms_dir))


if __name__ == '__main__':
    main()
